/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntityInContextRequest struct {
	EntityGuidPath string `json:"entityGuidPath,omitempty"`
	EntityBusinessIDPath string `json:"entityBusinessIDPath,omitempty"`
	ActivationDate string `json:"activationDate,omitempty"`
}
