/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Entity struct {
	Id string `json:"id,omitempty"`
	EntityID string `json:"entityID,omitempty"`
	ChildEntity []Entity `json:"childEntity,omitempty"`
	CharacteristicUse []CharacteristicUse `json:"characteristicUse,omitempty"`
	RateAttribute []RatingAttribute `json:"rateAttribute,omitempty"`
	ConfiguredValue []ConfiguredValueUse `json:"configuredValue,omitempty"`
	LinkedEntity []EntityLink `json:"linkedEntity,omitempty"`
	UnitQuantity string `json:"unitQuantity,omitempty"`
	IncludeTechnicalChildren bool `json:"includeTechnicalChildren,omitempty"`
	IsNewForCustomer bool `json:"isNewForCustomer,omitempty"`
	IsNewForCustomerSpecified bool `json:"isNewForCustomerSpecified,omitempty"`
}
