/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ProductCandidateDecomposeRequest struct {
	CreationDate time.Time `json:"creationDate,omitempty"`
	ProductCandidate *ProductCandidate `json:"productCandidate,omitempty"`
	ContextualParameter []RootContextualParameter `json:"contextualParameter,omitempty"`
}
