/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FindWithParametersFilters struct {
	Classifications string `json:"classifications,omitempty"`
	Characteristics string `json:"characteristics,omitempty"`
	FactElementFilter string `json:"factElementFilter,omitempty"`
	InstanceTypeName string `json:"instanceTypeName,omitempty"`
	Categories string `json:"categories,omitempty"`
	AvailableDate string `json:"availableDate,omitempty"`
}
