/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CharacteristicUse struct {
	UseArea string `json:"useArea,omitempty"`
	CharacteristicID string `json:"characteristicID,omitempty"`
	Value []CharacteristicValue `json:"value,omitempty"`
}
