/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FindFilteredParameters struct {
	TargetDate string `json:"targetDate,omitempty"`
	TargetTypes []string `json:"targetTypes,omitempty"`
	Classifications [][]string `json:"classifications,omitempty"`
	Select_ []string `json:"select,omitempty"`
}
