/*
 * Catalog Services API
 *
 * Catalog Services Web API Documentation
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntityLink struct {
	LinkTypeID string `json:"linkTypeID,omitempty"`
	Link []LinkTarget `json:"link,omitempty"`
}
